@startuml erd

hide circle
skinparam linetype ortho

entity "mUser" as mUser {
    *Id : nvarchar(450) <<auto>>
    --
    Email : nvarchar(200)
}

entity "mRole" as mRole {
    *Id : nvarchar(450) <<auto>>
    --
    Nama : varchar(200)
}

entity "mUserRole" as mUserRole {
    *Id_User : nvarchar(450) <<FK>>
    *Id_Role : nvarchar(450) <<FK>>
}

entity "mVendor" as mVendor {
    *Id : int <<auto>>
    --
    Id_User : nvarchar(450) <<FK>>
    Nama : varchar(200)
    Alamat : varchar(500) : NULL
    Telp : varchat(100) : NULL
}

entity "mAdmin" as mAdmin {
    *Id : int <<auto>>
    --
    Id_User : nvarchar(450) <<FK>>
    Nama : varchar(200)
    Telp : varchat(100) : NULL
}

entity "mCustomer" as mCustomer {
    *Id : int <<auto>>
    --
    Id_User : nvarchar(450) <<FK>>
    Nama : varchar(200)
    Alamat : varchar(500) : NULL
    Telp : varchat(100) : NULL
    FotoKTP : image : NULL
}

entity "mMerekKendaraan" as mMerekKendaraan {
    *Id : int <<auto>>
    --
    Nama : varchar(100)
}

entity "mJenisBahanBakar" as mJenisBahanBakar {
    *Id : int <<auto>>
    --
    Nama : varchar(100)
}

entity "mTipeKendaraan" as mTipeKendaraan {
    *Id : int <<auto>>
    --
    Id_MerekKendaraan : int <<FK>>
    Id_JenisBahanBakar : int <<FK>>
    Nama : varchar(100)
    Transmisi : varchar(20) : Matic, Manual
    Harga : money
}

entity "mKendaraan" as mKendaraan {
    *Id : int <<auto>>
    --
    Id_Vendor : int <<FK>>
    Id_TipeKendaraan : in <<FK>> 
    NoPolisi : varchar(50)
    TahunPembuatan : int : NULL
    Warna : varchar(50) : NULL
    Jenis : varchar() : Motor, Mobil
    TanggalSamsat : datetime : NULL
    TanggalSamsat5Tahun : datetime : NULL
    NomorMesin : varchar(50)
    STNKAtasNama : varchar(200)
    STNKAlamat : varchar(500)
    Foto : image : NULL
}

entity "trKondisiKendaraan" as trKondisiKendaraan {
    *Id : int <<auto>>
    --
    Id_Kendaraan : int <<FK>>
    Id_Admin : int <<FK>>
    Tanggal : datetime
    Kilometer : int : NULL
    Bensin : int : NULL
    Catatan : varchar(500) : NULL
    Kelengkapan : varchar(500) : NULL
}

entity "trKondisiKendaraanFoto" as trKondisiKendaraanFoto {
    *Id : int <<auto>>
    --
    Id_KondisiKendaraan : int <<FK>>
    Foto : image
}

entity "trSewa" as trSewa {
    *Id : int <<auto>>
    --
    NoBukti : varchar(50)
    Id_Kendaraan : int <<FK>>
    Id_Customer : int <<FK>>
    Id_Admin : int <<FK>>
    Tanggal : datetime
    TanggalSewa : datetime
    LamaSewa : int
    TanggalDiambil : datetime : NULL
    TanggalDikembalian : datetime : NULL
    Harga : money
    Batal : bool : NULL
}

entity "trSewaPerjanjian" as trSewaPerjanjian {
    *Id : int <<FK>>
    --
    Tanggal : datetime
    NamaUsaha : varchat(200)
    Telp : varchat(100)
    Alamat : varchat(500)
    Website : varchat(200)
}

entity "trSewaBiaya" as trSewaBiaya {
    *Id_Sewa : int <<FK>>
    *Id_JenisBiaya : int <<FK>>
    --
    Biaya : money
    Lunas : bool
    Catata : varchar(500) : NULL
    FotoBukti : image : NULL
}

entity "mJenisBiaya" as mJenisBiaya {
    *Id : int <<auto>>
    --
    Nama : varchar (200)
}

entity "mKonfigurasi" as mKonfigurasi {
    *Id : int <<auto>>
    --
    Nama : varchar(50)
    Value : varchar(1000)
}

mUser ||--o{ mUserRole
mRole ||--o{ mUserRole
mVendor ||--|| mUser
mAdmin ||--|| mUser
mCustomer ||--|| mUser
mVendor ||--|{ mKendaraan

trKondisiKendaraan }o--|| mKendaraan
trKondisiKendaraan }o--|| mAdmin
trKondisiKendaraan ||--o{ trKondisiKendaraanFoto

trSewa ||--|{ mKendaraan
trSewa ||--|{ mCustomer
trSewa ||--|{ mAdmin
trSewa ||--o| trSewaPerjanjian
trSewa ||--o{ trSewaBiaya
mJenisBiaya ||--o{ trSewaBiaya
mJenisBahanBakar ||--o{ mTipeKendaraan

mKendaraan ||--|{ mTipeKendaraan
mTipeKendaraan ||--|{ mMerekKendaraan

@enduml